### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by dh12121** [JohannesAutenrieb/MissileSimulation#1]
Hello, do you have the PDF document of the project? Could you please send me a copy

**Comment by JohannesAutenrieb** [comment]
Hi @LeshphonCry,

I've added the document of the lecturer, which introduces the problem. I didn't add my report. But I'm always happy to help, whenever you got further questions.

Best regards,
Johannes

**Comment by ashraf590** [comment]
dear Dr,
i have the same question about the document of lecturer
